name: deploy-production

on:
  push:
    branches: [ main ]

jobs:
  deploy-production:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.1'
    
    - name: Build
      run: hugo -v --minify